#!/bin/sh

case "$1" in
    *.png|*.jpg|*.jpeg|*.gif|*.webp|*.bmp)
        chafa --format=symbols --size="$2"x"$3" "$1"
        ;;
    *.pdf)
        pdftotext "$1" -
        ;;
    *)
        if file --mime-type --brief "$1" | grep -q "^text/"; then
            bat --color=always --style=full "$1"
        else
            file -L "$1"
        fi
        ;;
esac
